### ISSUE TITLE
Samples documentation issue

### ISSUE THREAD

**Issue by ryancrawcour** [Azure-Samples/aci-logicapps-integration#5]
the rendered published document found on https://azure.microsoft.com/en-us/resources/samples/aci-logicapps-integration/ does not render correctly. the images do not show properly, nor do any of the tables. 

reading directly in GitHub readme.md renders ok though.

**Comment by mmacy** [comment]
@jluk Do you know who's on the hook for maintaining these sample repos, by chance?

**Comment by jluk** [comment]
The vendors helped start it, but they are no longer here so I guess that falls on myself. ACOM doesn't have any documentation to my knowledge on what markdown works and what doesn't - making it really difficult to make sure it renders right everywhere.

@mmacy do you know of a doc like that, I'll have to just remove the table if it is not supported by ACOM.

**Comment by mmacy** [comment]
@jluk  The doc in the contributor's guide mentions nothing about Markdown support, so I'll pose a question to the internal team. Will let you know.

**Comment by jluk** [comment]
Adding @rbitia since she worked with the vendors on this example too, perhaps she can help in upkeep.

**Comment by mmacy** [comment]
@ryancrawcour Thanks for the report. I've filed a bug for this issue in ACOM's tracker, will update here as I receive updates.

**Comment by mmacy** [comment]
@ryancrawcour Late follow-up here, but the Azure Samples Browser has been updated significantly since this issue was opened, and images and tables are now rendered as expected. Here's this sample on the new Samples Browser:

https://docs.microsoft.com/samples/azure-samples/aci-logicapps-integration/aci-logicapps-integration/

Closing this one out - thanks again for the report.
